<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SDL3-CS\SDL3-CS.csproj" />
    <ProjectReference Include="..\SDL3-CS.Generators\SDL3-CS.Generators.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.4.0" />
  </ItemGroup>

</Project>
