using SDL3;

SDL3.Tests.SDL.Basics.Assert.PInvokeTests.ReportAssertion_ForwardsDataStringsAndLine();
Console.WriteLine("SDL.ReportAssertion binding test passed.");
SDL3.Tests.SDL.Basics.Assert.PInvokeTests.SetAssertionHandler_ForwardsHandlerAndUserdata();
Console.WriteLine("SDL.SetAssertionHandler binding test passed.");
SDL3.Tests.SDL.Basics.Assert.PInvokeTests.GetDefaultAssertionHandler_ReturnsNativeValue();
Console.WriteLine("SDL.GetDefaultAssertionHandler binding test passed.");
SDL3.Tests.SDL.Basics.Assert.PInvokeTests.GetAssertionHandler_ForwardsUserdataPointerAndReturnsNativeValue();
Console.WriteLine("SDL.GetAssertionHandler binding test passed.");
SDL3.Tests.SDL.Basics.Assert.PInvokeTests.GetAssertionReport_ReturnsNativePointer();
Console.WriteLine("SDL.GetAssertionReport binding test passed.");
SDL3.Tests.SDL.Basics.Assert.PInvokeTests.ResetAssertionReport_CallsNativeHook();
Console.WriteLine("SDL.ResetAssertionReport binding test passed.");
SDL3.Tests.SDL.Basics.Error.MacroTests.Unsupported_SetsStandardErrorAndReturnsFalse();
Console.WriteLine("SDL.Unsupported macro test passed.");
SDL3.Tests.SDL.Basics.Error.MacroTests.InvalidParamError_SetsParameterErrorAndReturnsFalse();
Console.WriteLine("SDL.InvalidParamError macro test passed.");
SDL3.Tests.SDL.Basics.Error.PInvokeTests.SetError_ForwardsMessageAndReturnsNativeValue();
Console.WriteLine("SDL.SetError binding test passed.");
SDL3.Tests.SDL.Basics.Error.PInvokeTests.SetErrorV_ForwardsFormatAndArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.SetErrorV binding test passed.");
SDL3.Tests.SDL.Basics.Error.PInvokeTests.OutOfMemory_ReturnsNativeValue();
Console.WriteLine("SDL.OutOfMemory binding test passed.");
SDL3.Tests.SDL.Basics.Error.PInvokeTests.SDL_GetError_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetError binding test passed.");
SDL3.Tests.SDL.Basics.Error.PInvokeTests.GetError_ReturnsUtf8StringAndEmpty();
Console.WriteLine("SDL.GetError binding test passed.");
SDL3.Tests.SDL.Basics.Error.PInvokeTests.ClearError_ReturnsNativeValue();
Console.WriteLine("SDL.ClearError binding test passed.");
SDL3.Tests.SDL.Basics.Hints.PInvokeTests.SetHintWithPriority_ForwardsNameValuePriorityAndReturnsNativeValue();
Console.WriteLine("SDL.SetHintWithPriority binding test passed.");
SDL3.Tests.SDL.Basics.Hints.PInvokeTests.SetHint_ForwardsNameValueAndReturnsNativeValue();
Console.WriteLine("SDL.SetHint binding test passed.");
SDL3.Tests.SDL.Basics.Hints.PInvokeTests.ResetHint_ForwardsNameAndReturnsNativeValue();
Console.WriteLine("SDL.ResetHint binding test passed.");
SDL3.Tests.SDL.Basics.Hints.PInvokeTests.ResetHints_CallsNativeHook();
Console.WriteLine("SDL.ResetHints binding test passed.");
SDL3.Tests.SDL.Basics.Hints.PInvokeTests.SDL_GetHint_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetHint binding test passed.");
SDL3.Tests.SDL.Basics.Hints.PInvokeTests.GetHint_ReturnsUtf8StringAndNull();
Console.WriteLine("SDL.GetHint binding test passed.");
SDL3.Tests.SDL.Basics.Hints.PInvokeTests.GetHintBoolean_ForwardsNameDefaultAndReturnsNativeValue();
Console.WriteLine("SDL.GetHintBoolean binding test passed.");
SDL3.Tests.SDL.Basics.Hints.PInvokeTests.AddHintCallback_ForwardsNameCallbackUserdataAndReturnsNativeValue();
Console.WriteLine("SDL.AddHintCallback binding test passed.");
SDL3.Tests.SDL.Basics.Hints.PInvokeTests.RemoveHintCallback_ForwardsNameCallbackUserdata();
Console.WriteLine("SDL.RemoveHintCallback binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.Init_ForwardsFlagsAndReturnsNativeValue();
Console.WriteLine("SDL.Init binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.InitSubSystem_ForwardsFlagsAndReturnsNativeValue();
Console.WriteLine("SDL.InitSubSystem binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.QuitSubSystem_ForwardsFlags();
Console.WriteLine("SDL.QuitSubSystem binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.WasInit_ForwardsFlagsAndReturnsNativeValue();
Console.WriteLine("SDL.WasInit binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.Quit_CallsNativeHook();
Console.WriteLine("SDL.Quit binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.IsMainThread_ReturnsNativeValue();
Console.WriteLine("SDL.IsMainThread binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.RunOnMainThread_ForwardsCallbackUserdataWaitAndReturnsNativeValue();
Console.WriteLine("SDL.RunOnMainThread binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.SetAppMetadata_ForwardsStringsAndReturnsNativeValue();
Console.WriteLine("SDL.SetAppMetadata binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.SetAppMetadataProperty_ForwardsStringsAndReturnsNativeValue();
Console.WriteLine("SDL.SetAppMetadataProperty binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.SDL_GetAppMetadataProperty_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAppMetadataProperty binding test passed.");
SDL3.Tests.SDL.Basics.Init.PInvokeTests.GetAppMetadataProperty_ReturnsUtf8StringAndNull();
Console.WriteLine("SDL.GetAppMetadataProperty binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.SetLogPriorities_ForwardsPriority();
Console.WriteLine("SDL.SetLogPriorities binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.SetLogPriority_ForwardsCategoryAndPriority();
Console.WriteLine("SDL.SetLogPriority binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.GetLogPriority_ForwardsCategoryAndReturnsNativeValue();
Console.WriteLine("SDL.GetLogPriority binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.ResetLogPriorities_CallsNativeHook();
Console.WriteLine("SDL.ResetLogPriorities binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.SetLogPriorityPrefix_ForwardsPriorityPrefixAndReturnsNativeValue();
Console.WriteLine("SDL.SetLogPriorityPrefix binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.Log_ForwardsFormat();
Console.WriteLine("SDL.Log binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.LogTrace_ForwardsCategoryAndFormat();
Console.WriteLine("SDL.LogTrace binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.LogVerbose_ForwardsCategoryAndFormat();
Console.WriteLine("SDL.LogVerbose binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.LogDebug_ForwardsCategoryAndMessage();
Console.WriteLine("SDL.LogDebug binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.LogInfo_ForwardsCategoryAndFormat();
Console.WriteLine("SDL.LogInfo binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.LogWarn_ForwardsCategoryAndFormat();
Console.WriteLine("SDL.LogWarn binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.LogError_ForwardsCategoryAndFormat();
Console.WriteLine("SDL.LogError binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.LogCritical_ForwardsCategoryAndFormat();
Console.WriteLine("SDL.LogCritical binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.LogMessage_ForwardsCategoryPriorityAndFormat();
Console.WriteLine("SDL.LogMessage binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.LogMessageV_ForwardsCategoryPriorityFormatAndArguments();
Console.WriteLine("SDL.LogMessageV binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.GetDefaultLogOutputFunction_ReturnsNativeValue();
Console.WriteLine("SDL.GetDefaultLogOutputFunction binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.GetLogOutputFunction_ReturnsCallbackAndUserdata();
Console.WriteLine("SDL.GetLogOutputFunction binding test passed.");
SDL3.Tests.SDL.Basics.Log.PInvokeTests.SetLogOutputFunction_ForwardsCallbackAndUserdata();
Console.WriteLine("SDL.SetLogOutputFunction binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.AppInit_ForwardsStateArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.AppInit binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.AppIterate_ForwardsStateAndReturnsNativeValue();
Console.WriteLine("SDL.AppIterate binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.AppEvent_ForwardsStateEventRefAndReturnsNativeValue();
Console.WriteLine("SDL.AppEvent binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.AppQuit_ForwardsStateAndResult();
Console.WriteLine("SDL.AppQuit binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.Main_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.Main binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.SetMainReady_CallsNativeHook();
Console.WriteLine("SDL.SetMainReady binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.RunApp_ForwardsArgumentsCallbackReservedAndReturnsNativeValue();
Console.WriteLine("SDL.RunApp binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.EnterAppMainCallbacks_ForwardsArgumentsAndCallbacksAndReturnsNativeValue();
Console.WriteLine("SDL.EnterAppMainCallbacks binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.RegisterApp_ForwardsNameStyleHInstAndReturnsNativeValue();
Console.WriteLine("SDL.RegisterApp binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.UnregisterApp_CallsNativeHook();
Console.WriteLine("SDL.UnregisterApp binding test passed.");
SDL3.Tests.SDL.Basics.Main.PInvokeTests.GDKSuspendComplete_CallsNativeHook();
Console.WriteLine("SDL.GDKSuspendComplete binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.GetGlobalProperties_ReturnsNativeValue();
Console.WriteLine("SDL.GetGlobalProperties binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.CreateProperties_ReturnsNativeValue();
Console.WriteLine("SDL.CreateProperties binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.CopyProperties_ForwardsSourceDestinationAndReturnsNativeValue();
Console.WriteLine("SDL.CopyProperties binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.LockProperties_ForwardsPropsAndReturnsNativeValue();
Console.WriteLine("SDL.LockProperties binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.UnlockProperties_ForwardsProps();
Console.WriteLine("SDL.UnlockProperties binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.SetPointerPropertyWithCleanup_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.SetPointerPropertyWithCleanup binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.SetPointerProperty_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.SetPointerProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.SetStringProperty_ForwardsNameValueAndNullAndReturnsNativeValue();
Console.WriteLine("SDL.SetStringProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.SetNumberProperty_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.SetNumberProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.SetFloatProperty_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.SetFloatProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.SetBooleanProperty_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.SetBooleanProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.HasProperty_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.HasProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.GetPropertyType_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.GetPropertyType binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.GetPointerProperty_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.GetPointerProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.SDL_GetStringProperty_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetStringProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.GetStringProperty_ReturnsUtf8StringAndEmpty();
Console.WriteLine("SDL.GetStringProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.GetNumberProperty_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.GetNumberProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.GetFloatProperty_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.GetFloatProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.GetBooleanProperty_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.GetBooleanProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.ClearProperty_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.ClearProperty binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.EnumerateProperties_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.EnumerateProperties binding test passed.");
SDL3.Tests.SDL.Basics.Properties.PInvokeTests.DestroyProperties_ForwardsProps();
Console.WriteLine("SDL.DestroyProperties binding test passed.");
SDL3.Tests.SDL.Basics.Version.MacroTests.VersionNum_ComposesNumericVersionAndKeepsMacroAttribute();
Console.WriteLine("SDL.VersionNum macro test passed.");
SDL3.Tests.SDL.Basics.Version.MacroTests.VersionNumMajor_ExtractsMajorAndKeepsMacroAttribute();
Console.WriteLine("SDL.VersionNumMajor macro test passed.");
SDL3.Tests.SDL.Basics.Version.MacroTests.VersionNumMinor_ExtractsMinorAndKeepsMacroAttribute();
Console.WriteLine("SDL.VersionNumMinor macro test passed.");
SDL3.Tests.SDL.Basics.Version.MacroTests.VersionNumMicro_ExtractsMicroAndKeepsMacroAttribute();
Console.WriteLine("SDL.VersionNumMicro macro test passed.");
SDL3.Tests.SDL.Basics.Version.PInvokeTests.GetVersion_ReturnsNativeValue();
Console.WriteLine("SDL.GetVersion binding test passed.");
SDL3.Tests.SDL.Basics.Version.PInvokeTests.SDL_GetRevision_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetRevision binding test passed.");
SDL3.Tests.SDL.Basics.Version.PInvokeTests.GetRevision_ReturnsUtf8StringAndEmpty();
Console.WriteLine("SDL.GetRevision binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.AsyncIOFromFile_ForwardsFileModeAndReturnsNativePointer();
Console.WriteLine("SDL.AsyncIOFromFile binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.GetAsyncIOSize_ForwardsAsyncioAndReturnsNativeValue();
Console.WriteLine("SDL.GetAsyncIOSize binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.ReadAsyncIO_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.ReadAsyncIO binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.WriteAsyncIO_ForwardsArgumentsAndReturnsNativeValue();
Console.WriteLine("SDL.WriteAsyncIO binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.CloseAsyncIO_ForwardsFlushAndReturnsNativeValue();
Console.WriteLine("SDL.CloseAsyncIO binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.CreateAsyncIOQueue_ReturnsNativePointer();
Console.WriteLine("SDL.CreateAsyncIOQueue binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.DestroyAsyncIOQueue_ForwardsQueue();
Console.WriteLine("SDL.DestroyAsyncIOQueue binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.GetAsyncIOResult_ForwardsQueueAndReturnsOutcome();
Console.WriteLine("SDL.GetAsyncIOResult binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.WaitAsyncIOResult_ForwardsQueueTimeoutAndReturnsOutcome();
Console.WriteLine("SDL.WaitAsyncIOResult binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.SignalAsyncIOQueue_ForwardsQueue();
Console.WriteLine("SDL.SignalAsyncIOQueue binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Asyncio.PInvokeTests.LoadFileAsync_ForwardsFileQueueUserdataAndReturnsNativeValue();
Console.WriteLine("SDL.LoadFileAsync binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.SDL_GetBasePath_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetBasePath binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.GetBasePath_ReturnsUtf8StringAndNull();
Console.WriteLine("SDL.GetBasePath binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.SDL_GetPrefPath_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetPrefPath binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.GetPrefPath_ForwardsOrgAppReturnsStringAndNull();
Console.WriteLine("SDL.GetPrefPath binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.SDL_GetUserFolder_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetUserFolder binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.GetUserFolder_ForwardsFolderReturnsStringAndNull();
Console.WriteLine("SDL.GetUserFolder binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.CreateDirectory_ForwardsPathAndReturnsNativeValue();
Console.WriteLine("SDL.CreateDirectory binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.EnumerateDirectory_ForwardsPathCallbackUserdataAndReturnsNativeValue();
Console.WriteLine("SDL.EnumerateDirectory binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.RemovePath_ForwardsPathAndReturnsNativeValue();
Console.WriteLine("SDL.RemovePath binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.RenamePath_ForwardsPathsAndReturnsNativeValue();
Console.WriteLine("SDL.RenamePath binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.CopyFile_ForwardsPathsAndReturnsNativeValue();
Console.WriteLine("SDL.CopyFile binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.GetPathInfo_ForwardsPathAndReturnsInfo();
Console.WriteLine("SDL.GetPathInfo binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.SDL_GlobDirectory_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GlobDirectory binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.GlobDirectory_ForwardsArgumentsReturnsArrayAndNull();
Console.WriteLine("SDL.GlobDirectory binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.SDL_GetCurrentDirectory_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetCurrentDirectory binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Filesystem.PInvokeTests.GetCurrentDirectory_ReturnsStringAndNull();
Console.WriteLine("SDL.GetCurrentDirectory binding test passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Iostream.PInvokeTests.RunAll();
Console.WriteLine("SDL.IOStream binding tests passed.");
SDL3.Tests.SDL.FileAndIOAbstractions.Storage.PInvokeTests.RunAll();
Console.WriteLine("SDL.Storage binding tests passed.");
SDL3.Tests.SDL.ForceFeedback.Haptic.PInvokeTests.RunAll();
Console.WriteLine("SDL.Haptic binding tests passed.");
SDL3.Tests.SDL.GPU.Gpu.PInvokeTests.RunAll();
Console.WriteLine("SDL.GPU binding tests passed.");
SDL3.Tests.SDL.InputEvents.Events.PInvokeTests.RunAll();
Console.WriteLine("SDL.Events binding tests passed.");
SDL3.Tests.SDL.InputEvents.Gamepad.PInvokeTests.RunAll();
Console.WriteLine("SDL.Gamepad binding tests passed.");
SDL3.Tests.SDL.InputEvents.Hidapi.PInvokeTests.RunAll();
Console.WriteLine("SDL.HIDAPI binding tests passed.");
SDL3.Tests.SDL.InputEvents.Joystick.PInvokeTests.RunAll();
Console.WriteLine("SDL.Joystick binding tests passed.");
SDL3.Tests.SDL.InputEvents.Keyboard.PInvokeTests.RunAll();
Console.WriteLine("SDL.Keyboard binding tests passed.");
SDL3.Tests.SDL.InputEvents.Keycode.MacroTests.ScancodeToKeycode_CombinesScancodeWithMaskAndKeepsMacroAttribute();
Console.WriteLine("SDL.ScancodeToKeycode macro test passed.");
SDL3.Tests.SDL.InputEvents.Mouse.MacroTests.ButtonMask_ShiftsButtonNumberAndKeepsMacroAttribute();
Console.WriteLine("SDL.ButtonMask macro test passed.");
SDL3.Tests.SDL.InputEvents.Mouse.PInvokeTests.RunAll();
Console.WriteLine("SDL.Mouse binding tests passed.");
SDL3.Tests.SDL.InputEvents.Pen.PInvokeTests.RunAll();
Console.WriteLine("SDL.Pen binding tests passed.");
SDL3.Tests.SDL.InputEvents.Sensor.PInvokeTests.RunAll();
Console.WriteLine("SDL.Sensor binding tests passed.");
SDL3.Tests.SDL.InputEvents.Touch.PInvokeTests.RunAll();
Console.WriteLine("SDL.Touch binding tests passed.");
SDL3.Tests.SDL.PlatformAndCPUInformation.Cpuinfo.PInvokeTests.RunAll();
Console.WriteLine("SDL.CPUInfo binding tests passed.");
SDL3.Tests.SDL.PlatformAndCPUInformation.Platform.PInvokeTests.RunAll();
Console.WriteLine("SDL.Platform binding tests passed.");
SDL3.Tests.SDL.SDLTests.RunAll();
Console.WriteLine("SDL helper tests passed.");
SDL3.Tests.SDL.WCharStringMarshallerTests.RunAll();
Console.WriteLine("SDL wide-char marshaller tests passed.");
SDL3.Tests.SDL.StreamTests.RunAll();
Console.WriteLine("SDL stream helper tests passed.");
SDL3.Tests.SDL.Threads.Atomic.MacroTests.RunAll();
Console.WriteLine("SDL.Atomic macro tests passed.");
SDL3.Tests.SDL.Threads.Atomic.PInvokeTests.RunAll();
Console.WriteLine("SDL.Atomic binding tests passed.");
SDL3.Tests.SDL.Threads.Mutex.PInvokeTests.RunAll();
Console.WriteLine("SDL.Mutex binding tests passed.");
SDL3.Tests.SDL.Threads.Thread.PInvokeTests.RunAll();
Console.WriteLine("SDL.Thread binding tests passed.");
SDL3.Tests.SDL.Time.Time.PInvokeTests.RunAll();
Console.WriteLine("SDL.Time binding tests passed.");
SDL3.Tests.SDL.Time.Timer.MacroTests.RunAll();
Console.WriteLine("SDL.Timer macro tests passed.");
SDL3.Tests.SDL.Time.Timer.PInvokeTests.RunAll();
Console.WriteLine("SDL.Timer binding tests passed.");
SDL3.Tests.SDL.Video.BlendMode.PInvokeTests.RunAll();
Console.WriteLine("SDL.BlendMode binding tests passed.");
SDL3.Tests.SDL.Video.Camera.PInvokeTests.RunAll();
Console.WriteLine("SDL.Camera binding tests passed.");
SDL3.Tests.SDL.Video.Clipboard.PInvokeTests.RunAll();
Console.WriteLine("SDL.Clipboard binding tests passed.");
SDL3.Tests.SDL.Video.Metal.PInvokeTests.RunAll();
Console.WriteLine("SDL.Metal binding tests passed.");
SDL3.Tests.SDL.Video.Pixels.MacroTests.RunAll();
Console.WriteLine("SDL.Pixels macro tests passed.");
SDL3.Tests.SDL.Video.Pixels.PInvokeTests.RunAll();
Console.WriteLine("SDL.Pixels binding tests passed.");
SDL3.Tests.SDL.Video.Rect.PInvokeTests.RunAll();
Console.WriteLine("SDL.Rect binding tests passed.");
SDL3.Tests.SDL.Video.Surface.MacroTests.RunAll();
Console.WriteLine("SDL.Surface macro tests passed.");
SDL3.Tests.SDL.Video.Surface.PInvokeTests.RunAll();
Console.WriteLine("SDL.Surface binding tests passed.");
SDL3.Tests.SDL.Video.Render.PInvokeTests.RunAll();
Console.WriteLine("SDL.Render binding tests passed.");
SDL3.Tests.SDL.Video.Video.MacroTests.RunAll();
Console.WriteLine("SDL.Video macro tests passed.");
SDL3.Tests.SDL.Video.Video.PInvokeTests.RunAll();
Console.WriteLine("SDL.Video binding tests passed.");
SDL3.Tests.SDL.Video.Vulkan.PInvokeTests.RunAll();
Console.WriteLine("SDL.Vulkan binding tests passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Dialog.DialogFileFilterTests.Dispose_FreesAllocatedUtf8PointersAndAllowsDefault();
Console.WriteLine("SDL.DialogFileFilter.Dispose binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Dialog.PInvokeTests.SDL_ShowOpenFileDialog_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_ShowOpenFileDialog binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Dialog.PInvokeTests.ShowOpenFileDialog_PinsFiltersAndConvertsDefaultLocation();
Console.WriteLine("SDL.ShowOpenFileDialog binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Dialog.PInvokeTests.SDL_ShowSaveFileDialog_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_ShowSaveFileDialog binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Dialog.PInvokeTests.ShowSaveFileDialog_PinsFiltersAndConvertsDefaultLocation();
Console.WriteLine("SDL.ShowSaveFileDialog binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Dialog.PInvokeTests.SDL_ShowOpenFolderDialog_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_ShowOpenFolderDialog binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Dialog.PInvokeTests.ShowOpenFolderDialog_ConvertsDefaultLocation();
Console.WriteLine("SDL.ShowOpenFolderDialog binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Dialog.PInvokeTests.ShowFileDialogWithProperties_ForwardsTypeUserdataAndProperties();
Console.WriteLine("SDL.ShowFileDialogWithProperties binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Guid.PInvokeTests.GUIDToString_WritesAsciiGuidString();
Console.WriteLine("SDL.GUIDToString binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Guid.PInvokeTests.StringToGUID_ParsesAsciiGuidString();
Console.WriteLine("SDL.StringToGUID binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Loadso.PInvokeTests.LoadObject_LoadsSdlLibraryAndReturnsNullForMissingFile();
Console.WriteLine("SDL.LoadObject binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Loadso.PInvokeTests.LoadFunction_ReturnsKnownSymbolAndNullForMissingSymbol();
Console.WriteLine("SDL.LoadFunction binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Loadso.PInvokeTests.UnloadObject_UnloadsLoadedLibrary();
Console.WriteLine("SDL.UnloadObject binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Locale.PInvokeTests.SDL_GetPreferredLocales_ReturnsNativeLocaleArray();
Console.WriteLine("SDL.SDL_GetPreferredLocales binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Locale.PInvokeTests.GetPreferredLocales_ConvertsNativeLocalesAndFreesArray();
Console.WriteLine("SDL.GetPreferredLocales binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Messagebox.PInvokeTests.ShowMessageBox_ForwardsDataAndButtonId();
Console.WriteLine("SDL.ShowMessageBox binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Messagebox.PInvokeTests.ShowSimpleMessageBox_ForwardsTextAndWindow();
Console.WriteLine("SDL.ShowSimpleMessageBox binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Misc.PInvokeTests.OpenURL_ForwardsUrl();
Console.WriteLine("SDL.OpenURL binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Power.PInvokeTests.GetPowerInfo_ReturnsStateAndOutputValues();
Console.WriteLine("SDL.GetPowerInfo binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Process.PInvokeTests.CreateProcess_StartsShortProcess();
Console.WriteLine("SDL.CreateProcess binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Process.PInvokeTests.CreateProcessWithProperties_StartsShortProcess();
Console.WriteLine("SDL.CreateProcessWithProperties binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Process.PInvokeTests.GetProcessProperties_ReturnsPropertiesForProcess();
Console.WriteLine("SDL.GetProcessProperties binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Process.PInvokeTests.ReadProcess_ReturnsOutputAndExitCode();
Console.WriteLine("SDL.ReadProcess binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Process.PInvokeTests.GetProcessInput_ReturnsStreamForPipedProcess();
Console.WriteLine("SDL.GetProcessInput binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Process.PInvokeTests.GetProcessOutput_ReturnsStreamForPipedProcess();
Console.WriteLine("SDL.GetProcessOutput binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Process.PInvokeTests.KillProcess_StopsRunningProcess();
Console.WriteLine("SDL.KillProcess binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Process.PInvokeTests.WaitProcess_ReportsShortProcessExit();
Console.WriteLine("SDL.WaitProcess binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Process.PInvokeTests.DestroyProcess_DestroysProcessHandle();
Console.WriteLine("SDL.DestroyProcess binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.MacroTests.FourCC_ComposesLittleEndianCode();
Console.WriteLine("SDL.FourCC binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.MacroTests.InitInterface_IOStreamInterface_SetsVersionAndClearsFields();
Console.WriteLine("SDL.InitInterface(IOStreamInterface) binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.MacroTests.InitInterface_StorageInterface_SetsVersionAndClearsFields();
Console.WriteLine("SDL.InitInterface(StorageInterface) binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.MacroTests.InitInterface_VirtualJoystickDesc_SetsVersionAndClearsFields();
Console.WriteLine("SDL.InitInterface(VirtualJoystickDesc) binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.Malloc_AllocatesWritableMemory();
Console.WriteLine("SDL.Malloc binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.Calloc_AllocatesZeroedMemory();
Console.WriteLine("SDL.Calloc binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.Realloc_ResizesAndPreservesMemory();
Console.WriteLine("SDL.Realloc binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.Free_FreesAllocatedMemoryAndAllowsNull();
Console.WriteLine("SDL.Free binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.GetOriginalMemoryFunctions_ReturnsCallableFunctions();
Console.WriteLine("SDL.GetOriginalMemoryFunctions binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.GetMemoryFunctions_ReturnsCallableFunctions();
Console.WriteLine("SDL.GetMemoryFunctions binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.SetMemoryFunctions_ForwardsCallbacksThroughHook();
Console.WriteLine("SDL.SetMemoryFunctions binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.AlignedAlloc_ReturnsAlignedMemory();
Console.WriteLine("SDL.AlignedAlloc binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.AlignedFree_FreesAlignedMemoryAndAllowsNull();
Console.WriteLine("SDL.AlignedFree binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.GetNumAllocations_ReturnsKnownSentinelOrCount();
Console.WriteLine("SDL.GetNumAllocations binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.GetEnvironment_ReturnsGlobalEnvironment();
Console.WriteLine("SDL.GetEnvironment binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.CreateEnvironment_CreatesEmptyAndPopulatedEnvironments();
Console.WriteLine("SDL.CreateEnvironment binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.SDL_GetEnvironmentVariable_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetEnvironmentVariable binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.GetEnvironmentVariable_ReturnsValueAndNull();
Console.WriteLine("SDL.GetEnvironmentVariable binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.SDL_GetEnvironmentVariables_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetEnvironmentVariables binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.GetEnvironmentVariables_ReturnsVariableArrayAndFreesNativeArray();
Console.WriteLine("SDL.GetEnvironmentVariables binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.SetEnvironmentVariable_SetsAndHonorsOverwrite();
Console.WriteLine("SDL.SetEnvironmentVariable binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.UnsetEnvironmentVariable_RemovesVariable();
Console.WriteLine("SDL.UnsetEnvironmentVariable binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.DestroyEnvironment_DestroysCreatedEnvironment();
Console.WriteLine("SDL.DestroyEnvironment binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.SRand_SeedsRandSequence();
Console.WriteLine("SDL.SRand binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.Rand_ReturnsValueWithinBound();
Console.WriteLine("SDL.Rand binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.RandF_ReturnsUnitRange();
Console.WriteLine("SDL.RandF binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.RandBits_ReturnsDeterministicValueAfterSeed();
Console.WriteLine("SDL.RandBits binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.RandR_ReturnsValueWithinBoundAndUpdatesState();
Console.WriteLine("SDL.RandR binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.RandFR_ReturnsUnitRangeAndUpdatesState();
Console.WriteLine("SDL.RandFR binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.RandBitsR_ReturnsValueAndUpdatesState();
Console.WriteLine("SDL.RandBitsR binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Stdinc.PInvokeTests.Memset_FillsMemoryAndReturnsDestination();
Console.WriteLine("SDL.Memset binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SetWindowsMessageHook_ForwardsCallbackAndUserdata();
Console.WriteLine("SDL.SetWindowsMessageHook binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetDirect3D9AdapterIndex_ForwardsDisplayID();
Console.WriteLine("SDL.GetDirect3D9AdapterIndex binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetDXGIOutputInfo_ForwardsDisplayIDAndOutputs();
Console.WriteLine("SDL.GetDXGIOutputInfo binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SetX11EventHook_ForwardsCallbackAndUserdata();
Console.WriteLine("SDL.SetX11EventHook binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SetLinuxThreadPriority_ForwardsThreadAndPriority();
Console.WriteLine("SDL.SetLinuxThreadPriority binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SetLinuxThreadPriorityAndPolicy_ForwardsThreadPriorityAndPolicy();
Console.WriteLine("SDL.SetLinuxThreadPriorityAndPolicy binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SetiOSAnimationCallback_ForwardsWindowIntervalCallbackAndParam();
Console.WriteLine("SDL.SetiOSAnimationCallback binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SetiOSEventPump_ForwardsEnabled();
Console.WriteLine("SDL.SetiOSEventPump binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetAndroidJNIEnv_ReturnsNativePointer();
Console.WriteLine("SDL.GetAndroidJNIEnv binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetAndroidActivity_ReturnsNativePointer();
Console.WriteLine("SDL.GetAndroidActivity binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetAndroidSDKVersion_ReturnsNativeValue();
Console.WriteLine("SDL.GetAndroidSDKVersion binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.IsChromebook_ReturnsNativeValue();
Console.WriteLine("SDL.IsChromebook binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.IsDeXMode_ReturnsNativeValue();
Console.WriteLine("SDL.IsDeXMode binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SendAndroidBackButton_ForwardsCall();
Console.WriteLine("SDL.SendAndroidBackButton binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SDL_GetAndroidInternalStoragePath_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAndroidInternalStoragePath binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetAndroidInternalStoragePath_ReturnsStringAndNull();
Console.WriteLine("SDL.GetAndroidInternalStoragePath binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetAndroidExternalStorageState_ReturnsNativeValue();
Console.WriteLine("SDL.GetAndroidExternalStorageState binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SDL_GetAndroidExternalStoragePath_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAndroidExternalStoragePath binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetAndroidExternalStoragePath_ReturnsStringAndNull();
Console.WriteLine("SDL.GetAndroidExternalStoragePath binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SDL_GetAndroidCachePath_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAndroidCachePath binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetAndroidCachePath_ReturnsStringAndNull();
Console.WriteLine("SDL.GetAndroidCachePath binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.RequestAndroidPermission_ForwardsPermissionCallbackAndUserdata();
Console.WriteLine("SDL.RequestAndroidPermission binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.ShowAndroidToast_ForwardsMessageAndLayout();
Console.WriteLine("SDL.ShowAndroidToast binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.SendAndroidMessage_ForwardsCommandAndParam();
Console.WriteLine("SDL.SendAndroidMessage binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.IsTablet_ReturnsNativeValue();
Console.WriteLine("SDL.IsTablet binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.IsTV_ReturnsNativeValue();
Console.WriteLine("SDL.IsTV binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetSandbox_ReturnsNativeValue();
Console.WriteLine("SDL.GetSandbox binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.OnApplicationWillTerminate_ForwardsCall();
Console.WriteLine("SDL.OnApplicationWillTerminate binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.OnApplicationDidReceiveMemoryWarning_ForwardsCall();
Console.WriteLine("SDL.OnApplicationDidReceiveMemoryWarning binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.OnApplicationWillEnterBackground_ForwardsCall();
Console.WriteLine("SDL.OnApplicationWillEnterBackground binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.OnApplicationDidEnterBackground_ForwardsCall();
Console.WriteLine("SDL.OnApplicationDidEnterBackground binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.OnApplicationWillEnterForeground_ForwardsCall();
Console.WriteLine("SDL.OnApplicationWillEnterForeground binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.OnApplicationDidEnterForeground_ForwardsCall();
Console.WriteLine("SDL.OnApplicationDidEnterForeground binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.OnApplicationDidChangeStatusBarOrientation_ForwardsCall();
Console.WriteLine("SDL.OnApplicationDidChangeStatusBarOrientation binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetGDKTaskQueue_ReturnsOutputHandle();
Console.WriteLine("SDL.GetGDKTaskQueue binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.System.PInvokeTests.GetGDKDefaultUser_ReturnsOutputHandle();
Console.WriteLine("SDL.GetGDKDefaultUser binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.CreateTray_ForwardsIconAndTooltip();
Console.WriteLine("SDL.CreateTray binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.SetTrayIcon_ForwardsTrayAndIcon();
Console.WriteLine("SDL.SetTrayIcon binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.SetTrayTooltip_ForwardsTrayAndTooltip();
Console.WriteLine("SDL.SetTrayTooltip binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.CreateTrayMenu_ForwardsTray();
Console.WriteLine("SDL.CreateTrayMenu binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.CreateTraySubmenu_ForwardsEntry();
Console.WriteLine("SDL.CreateTraySubmenu binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.GetTrayMenu_ForwardsTray();
Console.WriteLine("SDL.GetTrayMenu binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.GetTraySubmenu_ForwardsEntry();
Console.WriteLine("SDL.GetTraySubmenu binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.SDL_GetTrayEntries_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetTrayEntries binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.GetTrayEntries_ReturnsPointerArrayAndNull();
Console.WriteLine("SDL.GetTrayEntries binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.RemoveTrayEntry_ForwardsEntry();
Console.WriteLine("SDL.RemoveTrayEntry binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.InsertTrayEntryAt_ForwardsMenuPositionLabelAndFlags();
Console.WriteLine("SDL.InsertTrayEntryAt binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.SetTrayEntryLabel_ForwardsEntryAndLabel();
Console.WriteLine("SDL.SetTrayEntryLabel binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.SDL_GetTrayEntryLabel_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetTrayEntryLabel binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.GetTrayEntryLabel_ReturnsStringAndNull();
Console.WriteLine("SDL.GetTrayEntryLabel binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.SetTrayEntryChecked_ForwardsEntryAndChecked();
Console.WriteLine("SDL.SetTrayEntryChecked binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.GetTrayEntryChecked_ReturnsNativeValue();
Console.WriteLine("SDL.GetTrayEntryChecked binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.SetTrayEntryEnabled_ForwardsEntryAndEnabled();
Console.WriteLine("SDL.SetTrayEntryEnabled binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.GetTrayEntryEnabled_ReturnsNativeValue();
Console.WriteLine("SDL.GetTrayEntryEnabled binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.SetTrayEntryCallback_ForwardsEntryCallbackAndUserdata();
Console.WriteLine("SDL.SetTrayEntryCallback binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.ClickTrayEntry_ForwardsEntry();
Console.WriteLine("SDL.ClickTrayEntry binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.DestroyTray_ForwardsTray();
Console.WriteLine("SDL.DestroyTray binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.GetTrayEntryParent_ForwardsEntry();
Console.WriteLine("SDL.GetTrayEntryParent binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.GetTrayMenuParentEntry_ForwardsMenu();
Console.WriteLine("SDL.GetTrayMenuParentEntry binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.GetTrayMenuParentTray_ForwardsMenu();
Console.WriteLine("SDL.GetTrayMenuParentTray binding test passed.");
SDL3.Tests.SDL.AdditionalFunctionality.Tray.PInvokeTests.UpdateTrays_ForwardsCall();
Console.WriteLine("SDL.UpdateTrays binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetNumAudioDrivers_ReturnsNativeValue();
Console.WriteLine("SDL.GetNumAudioDrivers binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SDL_GetAudioDriver_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAudioDriver binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioDriver_ReturnsStringAndNull();
Console.WriteLine("SDL.GetAudioDriver binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SDL_GetCurrentAudioDriver_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetCurrentAudioDriver binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetCurrentAudioDriver_ReturnsStringAndNull();
Console.WriteLine("SDL.GetCurrentAudioDriver binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SDL_GetAudioPlaybackDevices_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAudioPlaybackDevices binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioPlaybackDevices_ReturnsDeviceArrayAndNull();
Console.WriteLine("SDL.GetAudioPlaybackDevices binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SDL_GetAudioRecordingDevices_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAudioRecordingDevices binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioRecordingDevices_ReturnsDeviceArrayAndNull();
Console.WriteLine("SDL.GetAudioRecordingDevices binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SDL_GetAudioDeviceName_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAudioDeviceName binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioDeviceName_ReturnsStringAndNull();
Console.WriteLine("SDL.GetAudioDeviceName binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioDeviceFormat_ForwardsDeviceAndOutputs();
Console.WriteLine("SDL.GetAudioDeviceFormat binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SDL_GetAudioDeviceChannelMap_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAudioDeviceChannelMap binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioDeviceChannelMap_ReturnsChannelArrayAndNull();
Console.WriteLine("SDL.GetAudioDeviceChannelMap binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.OpenAudioDevice_WithSpec_ForwardsDeviceAndSpec();
Console.WriteLine("SDL.OpenAudioDevice(in AudioSpec) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.OpenAudioDevice_WithPointer_ForwardsDeviceAndPointer();
Console.WriteLine("SDL.OpenAudioDevice(IntPtr) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.IsAudioDevicePhysical_ReturnsNativeValue();
Console.WriteLine("SDL.IsAudioDevicePhysical binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.IsAudioDevicePlayback_ReturnsNativeValue();
Console.WriteLine("SDL.IsAudioDevicePlayback binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.PauseAudioDevice_ReturnsNativeValue();
Console.WriteLine("SDL.PauseAudioDevice binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.ResumeAudioDevice_ReturnsNativeValue();
Console.WriteLine("SDL.ResumeAudioDevice binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.AudioDevicePaused_ReturnsNativeValue();
Console.WriteLine("SDL.AudioDevicePaused binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioDeviceGain_ReturnsNativeValue();
Console.WriteLine("SDL.GetAudioDeviceGain binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SetAudioDeviceGain_ForwardsDeviceAndGain();
Console.WriteLine("SDL.SetAudioDeviceGain binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.CloseAudioDevice_ForwardsDevice();
Console.WriteLine("SDL.CloseAudioDevice binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.BindAudioStreams_ForwardsDeviceStreamsAndCount();
Console.WriteLine("SDL.BindAudioStreams binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.BindAudioStream_ForwardsDeviceAndStream();
Console.WriteLine("SDL.BindAudioStream binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.UnbindAudioStreams_ForwardsStreamsAndCount();
Console.WriteLine("SDL.UnbindAudioStreams binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.UnbindAudioStream_ForwardsStream();
Console.WriteLine("SDL.UnbindAudioStream binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamDevice_ReturnsNativeValue();
Console.WriteLine("SDL.GetAudioStreamDevice binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.CreateAudioStream_WithPointers_ForwardsSpecs();
Console.WriteLine("SDL.CreateAudioStream(IntPtr, IntPtr) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.CreateAudioStream_WithSpecs_ForwardsSpecs();
Console.WriteLine("SDL.CreateAudioStream(in AudioSpec, in AudioSpec) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamProperties_ReturnsNativeValue();
Console.WriteLine("SDL.GetAudioStreamProperties binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamFormat_ForwardsStreamAndOutputs();
Console.WriteLine("SDL.GetAudioStreamFormat binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SetAudioStreamFormat_WithPointers_ForwardsStreamAndSpecs();
Console.WriteLine("SDL.SetAudioStreamFormat(IntPtr, IntPtr, IntPtr) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SetAudioStreamFormat_WithSpecs_ForwardsStreamAndSpecs();
Console.WriteLine("SDL.SetAudioStreamFormat(IntPtr, in AudioSpec, in AudioSpec) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamFrequencyRatio_ReturnsNativeValue();
Console.WriteLine("SDL.GetAudioStreamFrequencyRatio binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SetAudioStreamFrequencyRatio_ForwardsStreamAndRatio();
Console.WriteLine("SDL.SetAudioStreamFrequencyRatio binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamGain_ReturnsNativeValue();
Console.WriteLine("SDL.GetAudioStreamGain binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SetAudioStreamGain_ForwardsStreamAndGain();
Console.WriteLine("SDL.SetAudioStreamGain binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SDL_GetAudioStreamInputChannelMap_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAudioStreamInputChannelMap binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamInputChannelMap_ReturnsChannelArrayAndNull();
Console.WriteLine("SDL.GetAudioStreamInputChannelMap binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SDL_GetAudioStreamOutputChannelMap_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAudioStreamOutputChannelMap binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamOutputChannelMap_ReturnsChannelArrayAndNull();
Console.WriteLine("SDL.GetAudioStreamOutputChannelMap binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SetAudioStreamInputChannelMap_ForwardsStreamMapAndCount();
Console.WriteLine("SDL.SetAudioStreamInputChannelMap binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SetAudioStreamOutputChannelMap_ForwardsStreamMapAndCount();
Console.WriteLine("SDL.SetAudioStreamOutputChannelMap binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.PutAudioStreamData_WithPointer_ForwardsBufferAndLength();
Console.WriteLine("SDL.PutAudioStreamData(IntPtr) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.PutAudioStreamDataNoCopy_ForwardsBufferCallbackAndUserdata();
Console.WriteLine("SDL.PutAudioStreamDataNoCopy binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.PutAudioStreamData_WithBytes_ForwardsBufferAndLength();
Console.WriteLine("SDL.PutAudioStreamData(byte[]) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.PutAudioStreamPlanarData_ForwardsChannelBuffersAndCounts();
Console.WriteLine("SDL.PutAudioStreamPlanarData binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamData_WithPointer_ReturnsNativeValue();
Console.WriteLine("SDL.GetAudioStreamData(IntPtr) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamData_WithBytes_ReturnsNativeValue();
Console.WriteLine("SDL.GetAudioStreamData(byte[]) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamAvailable_ReturnsNativeValue();
Console.WriteLine("SDL.GetAudioStreamAvailable binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioStreamQueued_ReturnsNativeValue();
Console.WriteLine("SDL.GetAudioStreamQueued binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.FlushAudioStream_ReturnsNativeValue();
Console.WriteLine("SDL.FlushAudioStream binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.ClearAudioStream_ReturnsNativeValue();
Console.WriteLine("SDL.ClearAudioStream binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.PauseAudioStreamDevice_ReturnsNativeValue();
Console.WriteLine("SDL.PauseAudioStreamDevice binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.ResumeAudioStreamDevice_ReturnsNativeValue();
Console.WriteLine("SDL.ResumeAudioStreamDevice binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.AudioStreamDevicePaused_ReturnsNativeValue();
Console.WriteLine("SDL.AudioStreamDevicePaused binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.LockAudioStream_ReturnsNativeValue();
Console.WriteLine("SDL.LockAudioStream binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.UnlockAudioStream_ReturnsNativeValue();
Console.WriteLine("SDL.UnlockAudioStream binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SetAudioStreamGetCallback_ForwardsCallbackAndUserdata();
Console.WriteLine("SDL.SetAudioStreamGetCallback binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SetAudioStreamPutCallback_ForwardsCallbackAndUserdata();
Console.WriteLine("SDL.SetAudioStreamPutCallback binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.DestroyAudioStream_ForwardsStream();
Console.WriteLine("SDL.DestroyAudioStream binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.OpenAudioDeviceStream_WithSpec_ForwardsDeviceSpecCallbackAndUserdata();
Console.WriteLine("SDL.OpenAudioDeviceStream(in AudioSpec) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.OpenAudioDeviceStream_WithPointer_ForwardsDeviceSpecPointerCallbackAndUserdata();
Console.WriteLine("SDL.OpenAudioDeviceStream(IntPtr) binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SetAudioPostmixCallback_ForwardsDeviceCallbackAndUserdata();
Console.WriteLine("SDL.SetAudioPostmixCallback binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.LoadWAVIO_ForwardsSourceCloseFlagAndOutputs();
Console.WriteLine("SDL.LoadWAVIO binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.LoadWAV_ForwardsPathAndOutputs();
Console.WriteLine("SDL.LoadWAV binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.MixAudio_ForwardsPointersFormatLengthAndVolume();
Console.WriteLine("SDL.MixAudio binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.ConvertAudioSamples_ForwardsSpecsDataAndOutputs();
Console.WriteLine("SDL.ConvertAudioSamples binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.SDL_GetAudioFormatName_UsesExpectedNativeMetadata();
Console.WriteLine("SDL.SDL_GetAudioFormatName binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetAudioFormatName_ReturnsStringAndEmpty();
Console.WriteLine("SDL.GetAudioFormatName binding test passed.");
SDL3.Tests.SDL.Audio.Audio.PInvokeTests.GetSilenceValueForFormat_ReturnsNativeValue();
Console.WriteLine("SDL.GetSilenceValueForFormat binding test passed.");
SDL3.Tests.SDL.Audio.Audio.MacroTests.DefineAudioFormat_ComposesFormatBits();
Console.WriteLine("SDL.DefineAudioFormat binding test passed.");
SDL3.Tests.SDL.Audio.Audio.MacroTests.AudioBitSize_ReturnsLowByte();
Console.WriteLine("SDL.AudioBitSize binding test passed.");
SDL3.Tests.SDL.Audio.Audio.MacroTests.AudioByteSize_ReturnsBitSizeDividedByEight();
Console.WriteLine("SDL.AudioByteSize binding test passed.");
SDL3.Tests.SDL.Audio.Audio.MacroTests.AudioIsFloat_ReportsFloatFlag();
Console.WriteLine("SDL.AudioIsFloat binding test passed.");
SDL3.Tests.SDL.Audio.Audio.MacroTests.AudioIsBigEndian_ReportsEndianFlag();
Console.WriteLine("SDL.AudioIsBigEndian binding test passed.");
SDL3.Tests.SDL.Audio.Audio.MacroTests.AudioIsLittleEndian_InvertsBigEndianFlag();
Console.WriteLine("SDL.AudioIsLittleEndian binding test passed.");
SDL3.Tests.SDL.Audio.Audio.MacroTests.AudioIsSigned_ReportsSignedFlag();
Console.WriteLine("SDL.AudioIsSigned binding test passed.");
SDL3.Tests.SDL.Audio.Audio.MacroTests.AudioIsInt_InvertsFloatFlag();
Console.WriteLine("SDL.AudioIsInt binding test passed.");
SDL3.Tests.SDL.Audio.Audio.MacroTests.AudioIsUnsigned_InvertsSignedFlag();
Console.WriteLine("SDL.AudioIsUnsigned binding test passed.");
SDL3.Tests.SDL.Audio.Audio.MacroTests.AudioFrameSize_MultipliesSampleBytesByChannels();
Console.WriteLine("SDL.AudioFrameSize binding test passed.");

SDL3.Tests.Image.PInvokeTests.Version_ReturnsLinkedSdlImageVersion();
Console.WriteLine("Image.Version binding test passed.");
SDL3.Tests.Image.PInvokeTests.Load_ReturnsNullForMissingFile();
SDL3.Tests.Image.PInvokeTests.Load_ReturnsSurfaceForBmpFile();
Console.WriteLine("Image.Load binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadIO_ReturnsNullForNullStream();
SDL3.Tests.Image.PInvokeTests.LoadIO_ReturnsSurfaceAndClosesOwnedStream();
Console.WriteLine("Image.LoadIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadTypedIO_ReturnsNullForNullStream();
SDL3.Tests.Image.PInvokeTests.LoadTypedIO_ReturnsSurfaceAndClosesOwnedStream();
Console.WriteLine("Image.LoadTypedIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadTexture_ReturnsNullForMissingFile();
SDL3.Tests.Image.PInvokeTests.LoadTexture_ReturnsTextureForBmpFile();
Console.WriteLine("Image.LoadTexture binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadTextureIO_ReturnsNullForNullStream();
SDL3.Tests.Image.PInvokeTests.LoadTextureIO_ReturnsTextureAndClosesOwnedStream();
Console.WriteLine("Image.LoadTextureIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadTextureTypedIO_ReturnsNullForNullStream();
SDL3.Tests.Image.PInvokeTests.LoadTextureTypedIO_ReturnsTextureAndClosesOwnedStream();
Console.WriteLine("Image.LoadTextureTypedIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadGPUTexture_ReturnsNullForMissingFileWithoutGpuContext();
Console.WriteLine("Image.LoadGPUTexture binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadGPUTextureIO_ReturnsNullForNullStreamWithoutGpuContext();
Console.WriteLine("Image.LoadGPUTextureIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadGPUTextureTypedIO_ReturnsNullForNullStreamWithoutGpuContext();
Console.WriteLine("Image.LoadGPUTextureTypedIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.GetClipboardImage_IsCallableAndUsesExpectedEntryPoint();
Console.WriteLine("Image.GetClipboardImage binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsANI_DetectsAniHeader();
Console.WriteLine("Image.IsANI binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsAVIF_ReturnsFalseForUnknownData();
Console.WriteLine("Image.IsAVIF binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsCUR_DetectsCurHeader();
Console.WriteLine("Image.IsCUR binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsBMP_DetectsBmpHeader();
Console.WriteLine("Image.IsBMP binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsGIF_DetectsGifHeader();
Console.WriteLine("Image.IsGIF binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsICO_DetectsIcoHeader();
Console.WriteLine("Image.IsICO binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsJPG_DetectsJpegHeader();
Console.WriteLine("Image.IsJPG binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsJXL_ReturnsFalseForUnknownData();
Console.WriteLine("Image.IsJXL binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsLBM_DetectsLbmHeader();
Console.WriteLine("Image.IsLBM binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsPCX_DetectsPcxHeader();
Console.WriteLine("Image.IsPCX binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsPNG_DetectsPngHeader();
Console.WriteLine("Image.IsPNG binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsPNM_DetectsPnmHeader();
Console.WriteLine("Image.IsPNM binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsQOI_DetectsQoiHeader();
Console.WriteLine("Image.IsQOI binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsSVG_DetectsSvgTag();
Console.WriteLine("Image.IsSVG binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsTIF_DetectsTifHeader();
Console.WriteLine("Image.IsTIF binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsWEBP_DetectsWebpHeader();
Console.WriteLine("Image.IsWEBP binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsXCF_DetectsXcfHeader();
Console.WriteLine("Image.IsXCF binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsXPM_DetectsXpmHeader();
Console.WriteLine("Image.IsXPM binding test passed.");
SDL3.Tests.Image.PInvokeTests.IsXV_DetectsXvHeader();
Console.WriteLine("Image.IsXV binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadAVIFIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadAVIFIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadBMPIO_ReturnsSurfaceForBmpStream();
Console.WriteLine("Image.LoadBMPIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadCURIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadCURIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadGIFIO_ReturnsSurfaceForGifStream();
Console.WriteLine("Image.LoadGIFIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadICOIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadICOIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadJPGIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadJPGIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadJXLIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadJXLIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadLBMIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadLBMIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadPCXIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadPCXIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadPNGIO_ReturnsSurfaceForPngStream();
Console.WriteLine("Image.LoadPNGIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadPNMIO_ReturnsSurfaceForPnmStream();
Console.WriteLine("Image.LoadPNMIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadSVGIO_ReturnsSurfaceForSvgStream();
Console.WriteLine("Image.LoadSVGIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadSizedSVGIO_ReturnsSurfaceForSizedSvgStream();
Console.WriteLine("Image.LoadSizedSVGIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadQOIIO_ReturnsSurfaceForQoiStream();
Console.WriteLine("Image.LoadQOIIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadTGAIO_ReturnsSurfaceForTgaStream();
Console.WriteLine("Image.LoadTGAIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadTIFIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadTIFIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadWEBPIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadWEBPIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadXCFIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadXCFIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadXPMIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadXPMIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadXVIO_ReturnsSurfaceForXvStream();
Console.WriteLine("Image.LoadXVIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.ReadXPMFromArray_ReturnsSurfaceForValidXpmArray();
Console.WriteLine("Image.ReadXPMFromArray binding test passed.");
SDL3.Tests.Image.PInvokeTests.ReadXPMFromArrayToRGB888_ReturnsSurfaceForValidXpmArray();
Console.WriteLine("Image.ReadXPMFromArrayToRGB888 binding test passed.");
SDL3.Tests.Image.PInvokeTests.Save_ReturnsTrueForBmpFile();
Console.WriteLine("Image.Save binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveTypedIO_ReturnsTrueForBmpStream();
Console.WriteLine("Image.SaveTypedIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveAVIF_ReturnsFalseForNullSurface();
Console.WriteLine("Image.SaveAVIF binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveAVIFIO_ReturnsFalseForNullSurface();
Console.WriteLine("Image.SaveAVIFIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveBMP_ReturnsTrueForBmpFile();
Console.WriteLine("Image.SaveBMP binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveBMPIO_ReturnsTrueForBmpStream();
Console.WriteLine("Image.SaveBMPIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveCUR_ReturnsTrueForCurFile();
Console.WriteLine("Image.SaveCUR binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveCURIO_ReturnsTrueForCurStream();
Console.WriteLine("Image.SaveCURIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveGIF_ReturnsTrueForGifFile();
Console.WriteLine("Image.SaveGIF binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveGIFIO_ReturnsTrueForGifStream();
Console.WriteLine("Image.SaveGIFIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveICO_ReturnsTrueForIcoFile();
Console.WriteLine("Image.SaveICO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveICOIO_ReturnsTrueForIcoStream();
Console.WriteLine("Image.SaveICOIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveJPG_ReturnsTrueForJpgFile();
Console.WriteLine("Image.SaveJPG binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveJPGIO_ReturnsTrueForJpgStream();
Console.WriteLine("Image.SaveJPGIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SavePNG_ReturnsTrueForPngFile();
Console.WriteLine("Image.SavePNG binding test passed.");
SDL3.Tests.Image.PInvokeTests.SavePNGIO_ReturnsTrueForPngStream();
Console.WriteLine("Image.SavePNGIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveTGA_ReturnsTrueForTgaFile();
Console.WriteLine("Image.SaveTGA binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveTGAIO_ReturnsTrueForTgaStream();
Console.WriteLine("Image.SaveTGAIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveWEBP_ReturnsTrueForWebpFile();
Console.WriteLine("Image.SaveWEBP binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveWEBPIO_ReturnsTrueForWebpStream();
Console.WriteLine("Image.SaveWEBPIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadAnimation_ReturnsAnimationForGifFile();
Console.WriteLine("Image.LoadAnimation binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadAnimationIO_ReturnsAnimationForGifStream();
Console.WriteLine("Image.LoadAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadAnimationTypedIO_ReturnsAnimationForGifStream();
Console.WriteLine("Image.LoadAnimationTypedIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadANIAnimationIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadANIAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadAPNGAnimationIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadAPNGAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadAVIFAnimationIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadAVIFAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadGIFAnimationIO_ReturnsAnimationForGifStream();
Console.WriteLine("Image.LoadGIFAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.LoadWEBPAnimationIO_ReturnsNullForNullStream();
Console.WriteLine("Image.LoadWEBPAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveAnimation_ReturnsTrueForGifFile();
Console.WriteLine("Image.SaveAnimation binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveAnimationTypedIO_ReturnsTrueForGifStream();
Console.WriteLine("Image.SaveAnimationTypedIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveANIAnimationIO_ReturnsFalseForNullAnimation();
Console.WriteLine("Image.SaveANIAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveAPNGAnimationIO_ReturnsFalseForNullAnimation();
Console.WriteLine("Image.SaveAPNGAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveAVIFAnimationIO_ReturnsFalseForNullAnimation();
Console.WriteLine("Image.SaveAVIFAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveGIFAnimationIO_ReturnsTrueForGifStream();
Console.WriteLine("Image.SaveGIFAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.SaveWEBPAnimationIO_ReturnsFalseForNullAnimation();
Console.WriteLine("Image.SaveWEBPAnimationIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.CreateAnimatedCursor_ReturnsNullForNullAnimation();
Console.WriteLine("Image.CreateAnimatedCursor binding test passed.");
SDL3.Tests.Image.PInvokeTests.FreeAnimation_AcceptsNullAnimation();
Console.WriteLine("Image.FreeAnimation binding test passed.");
SDL3.Tests.Image.PInvokeTests.CreateAnimationEncoder_ReturnsEncoderForGifFile();
Console.WriteLine("Image.CreateAnimationEncoder binding test passed.");
SDL3.Tests.Image.PInvokeTests.CreateAnimationEncoderIO_ReturnsEncoderForGifStream();
Console.WriteLine("Image.CreateAnimationEncoderIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.CreateAnimationEncoderWithProperties_ReturnsEncoderForGifFile();
Console.WriteLine("Image.CreateAnimationEncoderWithProperties binding test passed.");
SDL3.Tests.Image.PInvokeTests.AddAnimationEncoderFrame_ReturnsTrueForGifEncoder();
Console.WriteLine("Image.AddAnimationEncoderFrame binding test passed.");
SDL3.Tests.Image.PInvokeTests.CloseAnimationEncoder_ReturnsTrueForGifEncoder();
Console.WriteLine("Image.CloseAnimationEncoder binding test passed.");
SDL3.Tests.Image.PInvokeTests.CreateAnimationDecoder_ReturnsDecoderForGifFile();
Console.WriteLine("Image.CreateAnimationDecoder binding test passed.");
SDL3.Tests.Image.PInvokeTests.CreateAnimationDecoderIO_ReturnsDecoderForGifStream();
Console.WriteLine("Image.CreateAnimationDecoderIO binding test passed.");
SDL3.Tests.Image.PInvokeTests.CreateAnimationDecoderWithProperties_ReturnsDecoderForGifStream();
Console.WriteLine("Image.CreateAnimationDecoderWithProperties binding test passed.");
SDL3.Tests.Image.PInvokeTests.GetAnimationDecoderProperties_ReturnsPropertiesForGifDecoder();
Console.WriteLine("Image.GetAnimationDecoderProperties binding test passed.");
SDL3.Tests.Image.PInvokeTests.GetAnimationDecoderFrame_ReturnsSurfaceForGifDecoder();
Console.WriteLine("Image.GetAnimationDecoderFrame binding test passed.");
SDL3.Tests.Image.PInvokeTests.GetAnimationDecoderStatus_ReturnsInvalidForNullDecoder();
Console.WriteLine("Image.GetAnimationDecoderStatus binding test passed.");
SDL3.Tests.Image.PInvokeTests.ResetAnimationDecoder_ReturnsTrueForGifDecoder();
Console.WriteLine("Image.ResetAnimationDecoder binding test passed.");
SDL3.Tests.Image.PInvokeTests.CloseAnimationDecoder_ReturnsTrueForGifDecoder();
Console.WriteLine("Image.CloseAnimationDecoder binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.Version_ReturnsLinkedSdlMixerVersion();
Console.WriteLine("Mixer.Version binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.Init_ReturnsTrueAndCanBeBalancedWithQuit();
Console.WriteLine("Mixer.Init binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.Quit_AllowsUninitializedAndBalancesInit();
Console.WriteLine("Mixer.Quit binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetNumAudioDecoders_ReturnsNonNegativeAfterInit();
Console.WriteLine("Mixer.GetNumAudioDecoders binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.MIX_GetAudioDecoder_ReturnsNullForInvalidIndex();
Console.WriteLine("Mixer.MIX_GetAudioDecoder binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetAudioDecoder_ReturnsNullForInvalidIndex();
Console.WriteLine("Mixer.GetAudioDecoder binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.CreateMixerDevice_ReturnsNullWhenMixerIsNotInitialized();
Console.WriteLine("Mixer.CreateMixerDevice binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.CreateMixer_ReturnsMixerForMemorySpec();
Console.WriteLine("Mixer.CreateMixer binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.DestroyMixer_DestroysMemoryMixer();
Console.WriteLine("Mixer.DestroyMixer binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetMixerProperties_ReturnsPropertiesForMemoryMixer();
Console.WriteLine("Mixer.GetMixerProperties binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetMixerFormat_ReturnsFormatForMemoryMixer();
Console.WriteLine("Mixer.GetMixerFormat binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.LoadAudioIO_ReturnsAudioForWavStream();
Console.WriteLine("Mixer.LoadAudioIO binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.LoadAudio_ReturnsAudioForWavFile();
Console.WriteLine("Mixer.LoadAudio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.LoadAudioWithProperties_ReturnsAudioForWavStreamProperties();
Console.WriteLine("Mixer.LoadAudioWithProperties binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.LoadAudioNoCopy_ReturnsAudioForPinnedWavData();
Console.WriteLine("Mixer.LoadAudioNoCopy binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.LoadRawAudioIO_ReturnsNullForNullInputs();
Console.WriteLine("Mixer.LoadRawAudioIO binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.LoadRawAudio_ReturnsNullForNullData();
Console.WriteLine("Mixer.LoadRawAudio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.LoadRawAudioNoCopy_ReturnsNullForNullData();
Console.WriteLine("Mixer.LoadRawAudioNoCopy binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.CreateSineWaveAudio_ReturnsAudioForMemoryMixer();
Console.WriteLine("Mixer.CreateSineWaveAudio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetAudioProperties_ReturnsPropertiesForLoadedAudio();
Console.WriteLine("Mixer.GetAudioProperties binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetAudioDuration_ReturnsKnownDurationForLoadedWav();
Console.WriteLine("Mixer.GetAudioDuration binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetAudioFormat_ReturnsFormatForLoadedWav();
Console.WriteLine("Mixer.GetAudioFormat binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.DestroyAudio_DestroysLoadedAudioAndAllowsNull();
Console.WriteLine("Mixer.DestroyAudio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.CreateTrack_ReturnsTrackForMemoryMixer();
Console.WriteLine("Mixer.CreateTrack binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.DestroyTrack_DestroysTrackAndAllowsNull();
Console.WriteLine("Mixer.DestroyTrack binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackProperties_ReturnsPropertiesForTrack();
Console.WriteLine("Mixer.GetTrackProperties binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackMixer_ReturnsOwningMixer();
Console.WriteLine("Mixer.GetTrackMixer binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackAudio_AssignsAndClearsAudio();
Console.WriteLine("Mixer.SetTrackAudio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackAudioStream_AssignsAndClearsStream();
Console.WriteLine("Mixer.SetTrackAudioStream binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackIOStream_AssignsAndClearsWavStream();
Console.WriteLine("Mixer.SetTrackIOStream binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackRawIOStream_ReturnsFalseForNullInputs();
Console.WriteLine("Mixer.SetTrackRawIOStream binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.TagTrack_AddsUtf8Tag();
Console.WriteLine("Mixer.TagTrack binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.UntagTrack_RemovesTagAndAllowsMissingTag();
Console.WriteLine("Mixer.UntagTrack binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.MIX_GetTrackTags_ReturnsNativeTagArray();
Console.WriteLine("Mixer.MIX_GetTrackTags binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackTags_ReturnsManagedTagsAndCount();
Console.WriteLine("Mixer.GetTrackTags binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.MIX_GetTaggedTracks_ReturnsNativeTrackArray();
Console.WriteLine("Mixer.MIX_GetTaggedTracks binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTaggedTracks_ReturnsManagedTrackPointersAndCount();
Console.WriteLine("Mixer.GetTaggedTracks binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackPlaybackPosition_SeeksAssignedStoppedTrack();
Console.WriteLine("Mixer.SetTrackPlaybackPosition binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackFadeFrames_ReturnsZeroForStoppedTrack();
Console.WriteLine("Mixer.GetTrackFadeFrames binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackPlaybackPosition_ReturnsPositionForAssignedStoppedTrack();
Console.WriteLine("Mixer.GetTrackPlaybackPosition binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackLoops_ReturnsZeroForStoppedTrack();
Console.WriteLine("Mixer.GetTrackLoops binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackLoops_ConfiguresAssignedTrack();
Console.WriteLine("Mixer.SetTrackLoops binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackAudio_ReturnsAssignedAudio();
Console.WriteLine("Mixer.GetTrackAudio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackAudioStream_ReturnsAssignedStream();
Console.WriteLine("Mixer.GetTrackAudioStream binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackRemaining_ReturnsZeroForAssignedStoppedTrack();
Console.WriteLine("Mixer.GetTrackRemaining binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.TrackMSToFrames_ConvertsMillisecondsForAssignedTrack();
Console.WriteLine("Mixer.TrackMSToFrames binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.TrackFramesToMS_ConvertsFramesForAssignedTrack();
Console.WriteLine("Mixer.TrackFramesToMS binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.AudioMSToFrames_ConvertsMillisecondsForAudio();
Console.WriteLine("Mixer.AudioMSToFrames binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.AudioFramesToMS_ConvertsFramesForAudio();
Console.WriteLine("Mixer.AudioFramesToMS binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.MSToFrames_ConvertsMillisecondsAtSampleRate();
Console.WriteLine("Mixer.MSToFrames binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.FramesToMS_ConvertsFramesAtSampleRate();
Console.WriteLine("Mixer.FramesToMS binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.PlayTrack_StartsAssignedTrack();
Console.WriteLine("Mixer.PlayTrack binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.PlayTag_StartsTaggedAssignedTrack();
Console.WriteLine("Mixer.PlayTag binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.PlayAudio_StartsFireAndForgetAudio();
Console.WriteLine("Mixer.PlayAudio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.StopTrack_StopsPlayingTrack();
Console.WriteLine("Mixer.StopTrack binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.StopAllTracks_StopsPlayingTracks();
Console.WriteLine("Mixer.StopAllTracks binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.StopTag_StopsTaggedPlayingTrack();
Console.WriteLine("Mixer.StopTag binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.PauseTrack_PausesPlayingTrack();
Console.WriteLine("Mixer.PauseTrack binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.PauseAllTracks_PausesPlayingTracks();
Console.WriteLine("Mixer.PauseAllTracks binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.PauseTag_PausesTaggedPlayingTrack();
Console.WriteLine("Mixer.PauseTag binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.ResumeTrack_ResumesPausedTrack();
Console.WriteLine("Mixer.ResumeTrack binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.ResumeAllTracks_ResumesPausedTracks();
Console.WriteLine("Mixer.ResumeAllTracks binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.ResumeTag_ResumesTaggedPausedTrack();
Console.WriteLine("Mixer.ResumeTag binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.TrackPlaying_ReportsPlayingState();
Console.WriteLine("Mixer.TrackPlaying binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.TrackPaused_ReportsPausedState();
Console.WriteLine("Mixer.TrackPaused binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetMixerGain_SetsGainForMemoryMixer();
Console.WriteLine("Mixer.SetMixerGain binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetMixerGain_ReturnsLastMixerGain();
Console.WriteLine("Mixer.GetMixerGain binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackGain_SetsGainForTrack();
Console.WriteLine("Mixer.SetTrackGain binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackGain_ReturnsLastTrackGain();
Console.WriteLine("Mixer.GetTrackGain binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTagGain_SetsGainForTaggedTrack();
Console.WriteLine("Mixer.SetTagGain binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetMixerFrequencyRatio_SetsRatioForMemoryMixer();
Console.WriteLine("Mixer.SetMixerFrequencyRatio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetMixerFrequencyRatio_ReturnsLastMixerRatio();
Console.WriteLine("Mixer.GetMixerFrequencyRatio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackFrequencyRatio_SetsRatioForTrack();
Console.WriteLine("Mixer.SetTrackFrequencyRatio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrackFrequencyRatio_ReturnsLastTrackRatio();
Console.WriteLine("Mixer.GetTrackFrequencyRatio binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackOutputChannelMap_SetsStereoSwapMap();
Console.WriteLine("Mixer.SetTrackOutputChannelMap binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackStereo_SetsAndClearsStereoGains();
Console.WriteLine("Mixer.SetTrackStereo binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrack3DPosition_SetsTrackPosition();
Console.WriteLine("Mixer.SetTrack3DPosition binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetTrack3DPosition_ReturnsLastTrackPosition();
Console.WriteLine("Mixer.GetTrack3DPosition binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.CreateGroup_ReturnsGroupForMemoryMixer();
Console.WriteLine("Mixer.CreateGroup binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.DestroyGroup_DestroysGroupAndAllowsNull();
Console.WriteLine("Mixer.DestroyGroup binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetGroupProperties_ReturnsPropertiesForGroup();
Console.WriteLine("Mixer.GetGroupProperties binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetGroupMixer_ReturnsOwningMixer();
Console.WriteLine("Mixer.GetGroupMixer binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackGroup_AssignsAndClearsGroup();
Console.WriteLine("Mixer.SetTrackGroup binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackStoppedCallback_SetsAndClearsCallback();
Console.WriteLine("Mixer.SetTrackStoppedCallback binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetTrackCookedCallback_SetsAndClearsCallback();
Console.WriteLine("Mixer.SetTrackCookedCallback binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetGroupPostMixCallback_SetsAndClearsCallback();
Console.WriteLine("Mixer.SetGroupPostMixCallback binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.SetPostMixCallback_SetsAndClearsCallback();
Console.WriteLine("Mixer.SetPostMixCallback binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.Generate_ReturnsMixedBytesForMemoryMixer();
Console.WriteLine("Mixer.Generate binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.CreateAudioDecoder_ReturnsDecoderForWavFile();
Console.WriteLine("Mixer.CreateAudioDecoder binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.CreateAudioDecoderIO_ReturnsDecoderForWavStream();
Console.WriteLine("Mixer.CreateAudioDecoderIO binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.DestroyAudioDecoder_DestroysDecoderAndAllowsNull();
Console.WriteLine("Mixer.DestroyAudioDecoder binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetAudioDecoderProperties_ReturnsPropertiesForDecoder();
Console.WriteLine("Mixer.GetAudioDecoderProperties binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.GetAudioDecoderFormat_ReturnsFormatForDecoder();
Console.WriteLine("Mixer.GetAudioDecoderFormat binding test passed.");
SDL3.Tests.Mixer.PInvokeTests.DecodeAudio_DecodesWavData();
Console.WriteLine("Mixer.DecodeAudio binding test passed.");
SDL3.Tests.TTF.PInvokeTests.RunAll();
Console.WriteLine("TTF binding tests passed.");
SDL3.Tests.ShaderCross.PInvokeTests.RunAll();
Console.WriteLine("ShaderCross binding tests passed.");

CreateAudioStreamWithNullSpecs nullSpecOverload = SDL.CreateAudioStream;
CreateAudioStreamWithTypedSpecs typedSpecOverload = SDL.CreateAudioStream;
SetAudioStreamFormatWithNullSpecs setAudioStreamFormatNull = SDL.SetAudioStreamFormat;
SetAudioStreamFormatWithTypedSpecs setAudioStreamFormatTyped = SDL.SetAudioStreamFormat;

GC.KeepAlive(nullSpecOverload);
GC.KeepAlive(typedSpecOverload);
GC.KeepAlive(setAudioStreamFormatNull);
GC.KeepAlive(setAudioStreamFormatTyped);

if (SDL.Hints.JoystickDrumDevices != "SDL_JOYSTICK_DRUM_DEVICES")
{
    throw new InvalidOperationException("Unexpected JoystickDrumDevices hint value.");
}

if (SDL.Hints.JoystickGuitarDevices != "SDL_JOYSTICK_GUITAR_DEVICES")
{
    throw new InvalidOperationException("Unexpected JoystickGuitarDevices hint value.");
}

if (SDL.Hints.JoystickGameInputRaw != "SDL_JOYSTICK_GAMEINPUT_RAW")
{
    throw new InvalidOperationException("Unexpected JoystickGameInputRaw hint value.");
}

if (SDL.Hints.VideoX11EnableXsyncExt != "SDL_VIDEO_X11_ENABLE_XSYNC_EXT")
{
    throw new InvalidOperationException("Unexpected VideoX11EnableXsyncExt hint value.");
}

if (SDL.Hints.WindowsRawKeyboardInputsink != "SDL_WINDOWS_RAW_KEYBOARD_INPUTSINK")
{
    throw new InvalidOperationException("Unexpected WindowsRawKeyboardInputsink hint value.");
}

if ((uint)SDL.EventType.WindowSettingsChanged != (uint)SDL.EventType.WindowHDRStateChanged + 1)
{
    throw new InvalidOperationException("Unexpected WindowSettingsChanged event value.");
}

if (SDL.EventType.WindowLast != SDL.EventType.WindowSettingsChanged)
{
    throw new InvalidOperationException("Unexpected WindowLast event value after visionOS settings sync.");
}

if (SDL.Props.WindowCreateVisionOSSettingsString != "SDL.window.create.visionos.settings")
{
    throw new InvalidOperationException("Unexpected WindowCreateVisionOSSettingsString property value.");
}

if (SDL.Props.WindowVisionOSSettingsString != "SDL.window.visionos.settings")
{
    throw new InvalidOperationException("Unexpected WindowVisionOSSettingsString property value.");
}

if (SDL.Props.TextInputTitleString != "SDL.textinput.title")
{
    throw new InvalidOperationException("Unexpected TextInputTitleString property value.");
}

if (SDL.Props.TextInputPlaceholderString != "SDL.textinput.placeholder")
{
    throw new InvalidOperationException("Unexpected TextInputPlaceholderString property value.");
}

if (SDL.Props.TextInputDefaultTextString != "SDL.textinput.default_text")
{
    throw new InvalidOperationException("Unexpected TextInputDefaultTextString property value.");
}

if (SDL.Props.TextInputMaxLengthNumber != "SDL.textinput.max_length")
{
    throw new InvalidOperationException("Unexpected TextInputMaxLengthNumber property value.");
}

if ((int)SDL.SystemCursor.ContextMenu != 20)
{
    throw new InvalidOperationException("Unexpected ContextMenu cursor value.");
}

if ((int)SDL.SystemCursor.ZoomOut != 33)
{
    throw new InvalidOperationException("Unexpected ZoomOut cursor value.");
}

if ((int)SDL.SystemCursor.SDLNumSystemCursors != 34)
{
    throw new InvalidOperationException("Unexpected SDLNumSystemCursors value after CSS cursor sync.");
}

if ((int)SDL.GamepadType.Steam != (int)SDL.GamepadType.GameCube + 1)
{
    throw new InvalidOperationException("Unexpected Steam gamepad type value.");
}

if ((int)SDL.GamepadType.Count != (int)SDL.GamepadType.Steam + 1)
{
    throw new InvalidOperationException("Unexpected gamepad type count after Steam insertion.");
}

Console.WriteLine("CreateAudioStream overload smoke test passed.");
Console.WriteLine("SetAudioStreamFormat overload smoke test passed.");
Console.WriteLine("Joystick device hint constants smoke test passed.");
Console.WriteLine("Joystick GameInput raw hint constant smoke test passed.");
Console.WriteLine("X11 XSync hint constant smoke test passed.");
Console.WriteLine("Windows raw keyboard input sink hint constant smoke test passed.");
Console.WriteLine("visionOS settings window constants smoke test passed.");
Console.WriteLine("Text input property constants smoke test passed.");
Console.WriteLine("CSS system cursor enum smoke test passed.");
Console.WriteLine("Steam gamepad type smoke test passed.");

delegate IntPtr CreateAudioStreamWithNullSpecs(IntPtr srcSpec, IntPtr dstSpec);

delegate IntPtr CreateAudioStreamWithTypedSpecs(in SDL.AudioSpec srcSpec, in SDL.AudioSpec dstSpec);

delegate bool SetAudioStreamFormatWithNullSpecs(IntPtr stream, IntPtr srcSpec, IntPtr dstSpec);

delegate bool SetAudioStreamFormatWithTypedSpecs(IntPtr stream, in SDL.AudioSpec srcSpec, in SDL.AudioSpec dstSpec);
