<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>28.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>org.libsdl.example.avaloniamixeraudio</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidUseFastDeployment>false</AndroidUseFastDeployment>
    <TrimMode>full</TrimMode>
    <SDL3CSExampleUseMixer>true</SDL3CSExampleUseMixer>
    <SDL3CSMixerVersion>3.2.4.9</SDL3CSMixerVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="12.1.0" />
  </ItemGroup>
</Project>
